---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true

---

# Plotly
* [Plotly](https://plotly-r.com/)

## Load package and data 

We're going look at NYC Airbnb data
```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)

install.packages("plotly")
```

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500) #price in the range of 100 to 500;
```

## Plotly Plots

### Scatterplot

use `?plotly()` if don't know 

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% #\n: next line;
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

# each plot will show the text with price and rating;
```

### Boxplot
Boxplot to show neighbouthood according to price

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% #reorder the plot according to the neighborhood and price;
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis") 
```

#### Violin
```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% #reorder the plot according to the neighborhood and price;
  plot_ly(y = ~price, color = ~neighbourhood, type = "violin", colors = "viridis") 
```

### Barchart

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>%  # count obs of each neighbourhood --> n;
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")

```

### ggplotly
convert a `ggplot` object straight to an interactive graphic using `ggplotly`.
```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()
scatter_ggplot

ggplotly(scatter_ggplot)
```

```{r}
box_ggplot = 
  nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

